name: Auto Release And Publish Website

on:
  - workflow_dispatch

jobs:
  call-shared-workflow:
    uses: Akito0723/auto-deploy/.github/workflows/Auto Release And Publish Website for node.yml@main
    with:
      node-version: "16.20.0"
      yarn-version: "1.22.19"
      deploy-path: "/var/www/docker-hub-mirror-web"
    secrets:
      RELEASE_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

