name: Auto Release And Deploy Website

on:
  - workflow_dispatch

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.next-latest-release.outputs.v-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get next version
        id: next-latest-release
        uses: reecetech/version-increment@2024.4.4
        with:
          scheme: calver

  auto-build-with-yarn:
    needs: get-next-version
    uses: Akito0723/auto-deploy/.github/workflows/Auto Build With yarn.yml@main
    with:
      node-version: "16.20.0"
      yarn-version: "1.22.19"
      tgz-file-name: release-${{ needs.get-next-version.outputs.release-version }}.tgz

  create-release:
    needs: [get-next-version, auto-build-with-yarn]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: ${{ needs.get-next-version.outputs.release-version }}
          name: Release ${{ needs.get-next-version.outputs.release-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # 要上传的文件
          files: ./release-${{ needs.get-next-version.outputs.release-version }}.tgz

  auto-deploy:
    needs: [get-next-version, auto-build-with-yarn]
    uses: Akito0723/auto-deploy/.github/workflows/Auto Deploy Website.yml@main
    with:
      tgz-file-name: release-${{ needs.get-next-version.outputs.release-version }}.tgz
      deploy-path: "/var/www/docker-hub-mirror-web"
